# Generated by Django 4.0.4 on 2022-06-05 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='descricao',
            field=models.TextField(max_length=250),
        ),
    ]
