# Generated by Django 4.0.4 on 2022-06-06 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_projeto_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadeira',
            name='anoLetivo',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='cadeira',
            name='descricao',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='descricao',
            field=models.TextField(max_length=400),
        ),
    ]
