# Generated by Django 4.0.4 on 2022-06-06 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_post_descricao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cadeira',
            old_name='linkedinPaginaCadeira',
            new_name='link',
        ),
    ]
